package com.example.leitor_json.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CandidatoDTO {
    private Double id;
    private String nomeUrna;
    private Integer numero;
    private Integer idCandidatoSuperior;
    private String nomeCompleto;
    private String descricaoSexo;
    private Date dataDeNascimento;
    private String tituloEleitor;
    private String cpf;
    private String descricaoEstadoCivil;
    private String descricaoCorRaca;
    private String descricaoSituacao;
    private String nacionalidade;
    private String grauInstrucao;
    private String ocupacao;
    private Float gastoCampanha1T;
    private Float gastoCampanha2T;
    private String sgUfNascimento;
    private String nomeMunicipioNascimento;
    private String localCandidatura;
    private String ufCandidatura;
    private String ufSuperiorCandidatura;
    private String dataUltimaAtualizacao;
    private String fotoUrl;
    private Date fotoDataUltimaAtualizacao;
    private String descricaoTotalizacao;
    private String nomeColigacao;
    private String composicaoColigacao;
    private String numeroProcessoDrap;
    private String numeroProcessoDrapEncrypt;
    private String numeroProcesso;
    private String numeroProcessoEncrypt;
    private String numeroProcessoPrestContas;
    private String numeroProcessoPrestContasEncrypt;
    private String numeroProtocolo;
    private CargoDTO cargo;
    private List<BemDTO> bens = new ArrayList<>();
    private Float totalDeBens;
    private List<ViceDTO> vices = new ArrayList<>();
    private PartidoDTO partido;
    private EleicaoDTO eleicao;
    private List<String> emails = new ArrayList<>();
    private List<String> sites = new ArrayList<>();
    private List<ArquivoDTO> arquivos = new ArrayList<>();
    private List<EleicaoAnteriorDTO> eleicoesAnteriores = new ArrayList<>();
    private String substituto;
    private String motivos;
    private Integer codigoSituacaoCandidato;
    private String descricaoSituacaoCandidato;
    private Boolean st_SUBSTITUIDO;
    private String descricaoNaturalidade;
    private Boolean st_MOTIVO_AUSENCIA_REQUISITO;
    private Boolean st_MOTIVO_CONDUTA_VEDADA;
    private String cnpjcampanha;
    private Float gastoCampanha;
    private Boolean st_MOTIVO_ABUSO_PODER;
    private Boolean st_MOTIVO_COMPRA_VOTO;
    private String ds_MOTIVO_OUTROS;
    private Boolean st_MOTIVO_GASTO_ILICITO;
    private Boolean st_MOTIVO_IND_PARTIDO;
    private Boolean st_MOTIVO_FICHA_LIMPA;
    private Boolean st_DIVULGA_ARQUIVOS;
    private Boolean st_DIVULGA_BENS;
    private Boolean st_DIVULGA;
    private Boolean st_REELEICAO;
}
